Seperate gyro sensitivity by axis
Rinnegatamante/vitaQuake pull request #61
Opened 2018-03-05 09:03 UTC by jakebriggs

Added in a separate sensitivity setting for each axis, changed the sensitivity setting to range from 0 to 10 rather than 1 to 11, so that turning the sensitivity down to 0 effectively turns off that axis.

2018-03-07 13:42 UTC, Rinnegatamante requested changes

2018-03-07 13:42 UTC, Rinnegatamante commented on source/menu.c
>  	if (options_cursor == OPTIONS_ITEMS) M_DrawCharacter (200, 252, 12+((int)(realtime*4)&1));
This must be updated to.

2018-03-07 19:46 UTC, jakebriggs commented
oh I was wondering how the cursor Y position matched the menu items. I'll tidy that right up

2018-03-09 07:03 UTC, jakebriggs commented
All fixed now

2018-03-09 13:26 UTC, merged